version: "2.13.0"

services:
    db:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - dir-site:/var/lib/mysql
    web:
        image: web
        build:
            dockerfile: ./docker/dockerfile
        container_name: web
        ports:
            - "8000:8000"
        hostname: admin
        working_dir: /project
        volumes:
            - .:/project
        depends_on:
            - db
        entrypoint: ./docker/wait-for-it.sh db:3306 -- bash ./docker/laravel.sh
        links:
            - db
volumes:
    dir-site:
