<?php

return [
    'number_day_limit_calendar' => 31,
    'check_switch' => [
        'date' => 'date',
        'week' => 'week',
    ],
    'number_minutes_freekey_time' => 30,
    'distance_between_landmarks_column_amount_of_sales' => 200,
    'distance_between_landmarks_column_amount_cancel' => 20,
    'first_year_in_list_years' => 2022,
    'yen_units_in_chart' => 10000,
    'precision_total_amount_chart' => 3,
    'color_categories' => [
        '#FF0000',
        '#FF00FF',
        '#008000',
        '#00FF00',
        '#FFFF00',
        '#6565eb',
        '#0000FF',
        '#008080',
        '#C0C0C0',
        '#00FFFF',
        '#e7f767',
        '#9b624c',
        '#07f2f3',
        '#91a3e9',
        '#c581b0',
        '#a188c1',
        '#b3e1d0',
        '#e1c073',
        '#ebaf25',
        '#ab37e5'
    ],
    'color_categories_null' => [
        '#a0dfbf',
        '#92cddb',
        '#f5f27e',
        '#f19d73',
        '#dbc9c0',
        '#0b8f03',
        '#c8abd9',
        '#e3a5c1',
        '#d5bbf1',
        '#007bff',
    ],
    'encrypt_secret_key' => env('ENCRYPT_SECRET_KEY', 'dHJhbiBuaGF0IHRoaWVuaWVu'),
    'secret_iv' => env('SECRET_IV', 'c2VjcmV0X2l2c2VjcmV0X2l2A'),
    'get_all' => 'all',
    'none' => 'none',
    'status_time' => [
        'start_date' => '1',
        'end_date' => '2',
        'start_operation_date' => '3',
        'end_operation_date' => '4',
    ],
];
